### ISSUE TITLE
error in macav2 ea calculation

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/MACA-ETr#1]
~Line: 351
#estimate sat. vapor press and use vpd
es = 0.6108*np.exp(17.27*self.data.tavg_c/(self.data.tavg_c+237.3))
self.data['ea_kpa'] = self.data.vapor_pres_def + es 
***VPD = es - ea; ea_kpa calc is incorrect 

Calculation should follow ASCE standardized refet Table 3 Preferred Procedure Order:
https://www.uidaho.edu/-/media/UIdaho-Responsive/Files/cals/centers/Kimberly/water-resources/ASCE-Standardized-Reference-Evapotranspiration-Equation-draft-report-without-appendices.pdf?la=en&hash=F4E3EB1290A7971E172F23A2A3B660B237D727D0 

Proposed Fix (use maca provided specific humidity): 
        if product == 'macav2':
            self.data['wind_mean'] = np.sqrt(
                self.data['eastward_wind']**2 + self.data['northward_wind']**2
            )
            self.data['pa'] =  np.full(length, refet.calcs._air_pressure(elev))
            self.data['ea_kpa'] = refet.calcs._actual_vapor_pressure(
                self.data.specific_humidity, self.data.pa
            )

**Comment by jhuntington** [comment]
Also, es should be computed using equation 6 and 7 in

https://www.uidaho.edu/-/media/UIdaho-Responsive/Files/cals/centers/Kimberly/water-resources/ASCE-Standardized-Reference-Evapotranspiration-Equation-draft-report-without-appendices.pdf?la=en&hash=F4E3EB1290A7971E172F23A2A3B660B237D727D0
we should not be using Tmean to compute es… we should be using Tmax and then Tmin, and then taking the average of es at Tmax and es at Tmin… the Temp and es function is an exponential… not linear.

Justin
